from __future__ import annotations

from botocore.exceptions import ClientError
from pydantic import BaseModel, ConfigDict

from aws_util._client import get_client

# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------


class EncryptResult(BaseModel):
    """Result of a KMS ``Encrypt`` call."""

    model_config = ConfigDict(frozen=True)

    ciphertext_blob: bytes
    key_id: str
    encryption_algorithm: str


class DataKey(BaseModel):
    """A data key generated by KMS for envelope encryption."""

    model_config = ConfigDict(frozen=True)

    plaintext: bytes
    """Raw plaintext data key — use immediately and discard from memory."""

    ciphertext_blob: bytes
    """Encrypted form of the data key — safe to store alongside ciphertext."""

    key_id: str


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------


def encrypt(
    key_id: str,
    plaintext: str | bytes,
    encryption_algorithm: str = "SYMMETRIC_DEFAULT",
    region_name: str | None = None,
) -> EncryptResult:
    """Encrypt data using a KMS key.

    Args:
        key_id: KMS key ID, alias (``"alias/my-key"``), or ARN.
        plaintext: Data to encrypt.  Strings are UTF-8 encoded automatically.
        encryption_algorithm: KMS encryption algorithm.  Use
            ``"SYMMETRIC_DEFAULT"`` (default) for symmetric keys.
        region_name: AWS region override.

    Returns:
        An :class:`EncryptResult` containing the ciphertext blob.

    Raises:
        RuntimeError: If encryption fails.
    """
    client = get_client("kms", region_name)
    raw = plaintext.encode("utf-8") if isinstance(plaintext, str) else plaintext
    try:
        resp = client.encrypt(
            KeyId=key_id,
            Plaintext=raw,
            EncryptionAlgorithm=encryption_algorithm,
        )
    except ClientError as exc:
        raise RuntimeError(f"Failed to encrypt with KMS key {key_id!r}: {exc}") from exc
    return EncryptResult(
        ciphertext_blob=resp["CiphertextBlob"],
        key_id=resp["KeyId"],
        encryption_algorithm=resp.get("EncryptionAlgorithm", encryption_algorithm),
    )


def decrypt(
    ciphertext_blob: bytes,
    key_id: str | None = None,
    encryption_algorithm: str = "SYMMETRIC_DEFAULT",
    region_name: str | None = None,
) -> bytes:
    """Decrypt a ciphertext blob using KMS.

    Args:
        ciphertext_blob: The encrypted bytes returned by :func:`encrypt`.
        key_id: KMS key ID, alias, or ARN.  Required for asymmetric keys;
            optional for symmetric keys (KMS infers the key from the
            ciphertext).
        encryption_algorithm: Algorithm that was used to encrypt the data.
        region_name: AWS region override.

    Returns:
        The original plaintext as bytes.

    Raises:
        RuntimeError: If decryption fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict = {
        "CiphertextBlob": ciphertext_blob,
        "EncryptionAlgorithm": encryption_algorithm,
    }
    if key_id is not None:
        kwargs["KeyId"] = key_id
    try:
        resp = client.decrypt(**kwargs)
    except ClientError as exc:
        raise RuntimeError(f"KMS decryption failed: {exc}") from exc
    return resp["Plaintext"]


def generate_data_key(
    key_id: str,
    key_spec: str = "AES_256",
    region_name: str | None = None,
) -> DataKey:
    """Generate a data key for envelope encryption.

    Use the returned plaintext key to encrypt your data locally, then store
    the encrypted ``ciphertext_blob`` alongside the data.  Discard the
    plaintext key from memory after use.

    Args:
        key_id: KMS CMK ID, alias, or ARN used to protect the data key.
        key_spec: ``"AES_256"`` (default) or ``"AES_128"``.
        region_name: AWS region override.

    Returns:
        A :class:`DataKey` with both the plaintext and encrypted key material.

    Raises:
        RuntimeError: If key generation fails.
    """
    client = get_client("kms", region_name)
    try:
        resp = client.generate_data_key(KeyId=key_id, KeySpec=key_spec)
    except ClientError as exc:
        raise RuntimeError(f"Failed to generate data key with KMS key {key_id!r}: {exc}") from exc
    return DataKey(
        plaintext=resp["Plaintext"],
        ciphertext_blob=resp["CiphertextBlob"],
        key_id=resp["KeyId"],
    )


# ---------------------------------------------------------------------------
# Complex utilities
# ---------------------------------------------------------------------------


def envelope_encrypt(
    key_id: str,
    plaintext: bytes | str,
    region_name: str | None = None,
) -> dict[str, bytes]:
    """Encrypt data using the envelope encryption pattern.

    Generates a one-time AES-256 data key via KMS, encrypts *plaintext*
    locally with AES-GCM, and returns both the ciphertext and the encrypted
    data key.  The plaintext data key never leaves memory after this call.

    Args:
        key_id: KMS CMK ID, alias (``"alias/my-key"``), or ARN.
        plaintext: Data to encrypt.  Strings are UTF-8 encoded.
        region_name: AWS region override.

    Returns:
        A dict with keys:
        - ``"ciphertext"`` — AES-GCM ciphertext bytes (nonce prepended)
        - ``"encrypted_data_key"`` — KMS-encrypted data key bytes (store
          alongside ciphertext; pass to :func:`envelope_decrypt`)

    Raises:
        RuntimeError: If KMS key generation fails.
    """
    import os

    from cryptography.hazmat.primitives.ciphers.aead import AESGCM

    data_key = generate_data_key(key_id, region_name=region_name)
    raw = plaintext.encode("utf-8") if isinstance(plaintext, str) else plaintext

    nonce = os.urandom(12)
    aesgcm = AESGCM(data_key.plaintext)
    ciphertext = nonce + aesgcm.encrypt(nonce, raw, None)

    # Zero out the plaintext key from the DataKey object immediately
    del aesgcm

    return {
        "ciphertext": ciphertext,
        "encrypted_data_key": data_key.ciphertext_blob,
    }


def envelope_decrypt(
    ciphertext: bytes,
    encrypted_data_key: bytes,
    region_name: str | None = None,
) -> bytes:
    """Decrypt data produced by :func:`envelope_encrypt`.

    Uses KMS to recover the data key, then decrypts the ciphertext locally
    with AES-GCM.

    Args:
        ciphertext: The ``"ciphertext"`` value returned by
            :func:`envelope_encrypt`.
        encrypted_data_key: The ``"encrypted_data_key"`` value returned by
            :func:`envelope_encrypt`.
        region_name: AWS region override.

    Returns:
        The original plaintext as bytes.

    Raises:
        RuntimeError: If KMS decryption or AES-GCM authentication fails.
    """
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM

    plaintext_key = decrypt_data_key(encrypted_data_key, region_name=region_name)
    nonce = ciphertext[:12]
    data = ciphertext[12:]
    aesgcm = AESGCM(plaintext_key)
    try:
        return aesgcm.decrypt(nonce, data, None)
    except Exception as exc:
        raise RuntimeError(f"envelope_decrypt failed: {exc}") from exc


def re_encrypt(
    ciphertext_blob: bytes,
    destination_key_id: str,
    source_key_id: str | None = None,
    region_name: str | None = None,
) -> EncryptResult:
    """Re-encrypt a ciphertext under a different KMS key without exposing the plaintext.

    Useful for key rotation: move data encrypted under an old key to a new key
    without decrypting it locally.  KMS performs the decrypt/re-encrypt
    operation entirely within the service boundary.

    Args:
        ciphertext_blob: Ciphertext bytes produced by :func:`encrypt`.
        destination_key_id: KMS key ID, alias, or ARN of the new key.
        source_key_id: KMS key ID, alias, or ARN of the current key.
            Required for asymmetric source keys; optional for symmetric keys.
        region_name: AWS region override.

    Returns:
        An :class:`EncryptResult` containing the re-encrypted ciphertext.

    Raises:
        RuntimeError: If re-encryption fails.
    """
    client = get_client("kms", region_name)
    kwargs: dict = {
        "CiphertextBlob": ciphertext_blob,
        "DestinationKeyId": destination_key_id,
    }
    if source_key_id is not None:
        kwargs["SourceKeyId"] = source_key_id
    try:
        resp = client.re_encrypt(**kwargs)
    except ClientError as exc:
        raise RuntimeError(f"Failed to re-encrypt to key {destination_key_id!r}: {exc}") from exc
    return EncryptResult(
        ciphertext_blob=resp["CiphertextBlob"],
        key_id=resp["KeyId"],
        encryption_algorithm=resp.get("DestinationEncryptionAlgorithm", "SYMMETRIC_DEFAULT"),
    )


def decrypt_data_key(
    ciphertext_blob: bytes,
    region_name: str | None = None,
) -> bytes:
    """Decrypt an encrypted data key generated by :func:`generate_data_key`.

    This is a convenience wrapper around :func:`decrypt` for the envelope
    encryption pattern.

    Args:
        ciphertext_blob: The ``ciphertext_blob`` field from a
            :class:`DataKey`.
        region_name: AWS region override.

    Returns:
        The plaintext data key as bytes.
    """
    return decrypt(ciphertext_blob=ciphertext_blob, region_name=region_name)
